### ISSUE TITLE
Doesn't work with newer pyflakes from default channel

### ISSUE THREAD

**Issue by janschulz** [conda-forge/flake8-feedstock#6] opened 2016-10-29 18:55 UTC
```
λ flake8.exe pypandoc
Traceback (most recent call last):
  File "C:\portabel\miniconda\lib\site-packages\setuptools-27.2.0-py3.5.egg\pkg_resources\__init__.py", line 660, in _build_master
  File "C:\portabel\miniconda\lib\site-packages\setuptools-27.2.0-py3.5.egg\pkg_resources\__init__.py", line 968, in require
  File "C:\portabel\miniconda\lib\site-packages\setuptools-27.2.0-py3.5.egg\pkg_resources\__init__.py", line 859, in resolve
pkg_resources.ContextualVersionConflict: (pyflakes 1.3.0 (c:\portabel\miniconda\lib\site-packages), Requirement.parse('pyflakes!=1.2.0,!=1.2.1,!=1.2.2,<1.3.0,>=0.8.1'), {'flake8'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\portabel\miniconda\Scripts\flake8-script.py", line 5, in <module>
    from pkg_resources import load_entry_point
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "C:\portabel\miniconda\lib\site-packages\setuptools-27.2.0-py3.5.egg\pkg_resources\__init__.py", line 2985, in <module>
  File "C:\portabel\miniconda\lib\site-packages\setuptools-27.2.0-py3.5.egg\pkg_resources\__init__.py", line 2971, in _call_aside
  File "C:\portabel\miniconda\lib\site-packages\setuptools-27.2.0-py3.5.egg\pkg_resources\__init__.py", line 2998, in _initialize_master_working_set
  File "C:\portabel\miniconda\lib\site-packages\setuptools-27.2.0-py3.5.egg\pkg_resources\__init__.py", line 662, in _build_master
  File "C:\portabel\miniconda\lib\site-packages\setuptools-27.2.0-py3.5.egg\pkg_resources\__init__.py", line 675, in _build_from_requirements
  File "C:\portabel\miniconda\lib\site-packages\setuptools-27.2.0-py3.5.egg\pkg_resources\__init__.py", line 854, in resolve
pkg_resources.DistributionNotFound: The 'pyflakes!=1.2.0,!=1.2.1,!=1.2.2,<1.3.0,>=0.8.1' distribution was not found and is required by flake8
```

```
λ conda list |grep flake
flake8                    3.0.4                    py35_0    conda-forge
pyflakes                  1.3.0                    py35_0    defaults
```

Downgrading fixed it for me:

```
λ conda install pyflakes=1.2
Fetching package metadata ...............
Solving package specifications: ..........

Package plan for installation in environment C:\portabel\miniconda:

The following packages will be SUPERCEDED by a higher-priority channel:

    pyflakes: 1.3.0-py35_0 defaults --> 1.2.3-py35_0 conda-forge
```

**Comment by croth1** [comment] 2016-10-31 18:42
flake8 pins the pyflakes version in its setup.py, see here: https://gitlab.com/pycqa/flake8/blob/master/setup.py#L17

3.0.4 version pinned pyflakes<1.3 and so do we in the meta.yaml. Should be expected behavior.

**Comment by croth1** [comment] 2016-10-31 18:45
I actually tried to pin pyflakes in meta.yaml. See https://github.com/conda-forge/flake8-feedstock/blob/master/recipe/meta.yaml#L30

Either the windows builds are not up-to-date, or the pinning didn't work as expected.

**Comment by dopplershift** [comment] 2016-11-02 22:21
Pinning might work now--there were 3 windows packages that originally failed to upload.

**Comment by janschulz** [comment] 2016-11-02 22:39
My guess would be that `conda update --all`doesn't respect internal consitency?

```
c:\data\external\python-appveyor-demo (master)
λ conda list flake8
# packages in environment at C:\portabel\miniconda:
#
flake8                    3.0.4                    py35_0    conda-forge
λ conda update --all                                                           
Fetching package metadata ...............                                      
Solving package specifications: ..........                                     
                                                                               
Package plan for installation in environment C:\portabel\miniconda:            
                                                                               
The following packages will be downloaded:                                     
                                                                               
    package                    |            build                              
    ---------------------------|-----------------                              
    conda-4.2.12               |           py35_0         446 KB  defaults     
    obvious-ci-0.6.1           |           py35_1         257 KB  conda-forge  
    conda-smithy-1.4.6         |           py35_0         294 KB  conda-forge  
    ------------------------------------------------------------               
                                           Total:         998 KB               
                                                                               
The following packages will be UPDATED:                                        
                                                                               
    conda:        4.2.11-py35_0 defaults    --> 4.2.12-py35_0 defaults         
    conda-smithy: 1.4.3-py35_0  conda-forge --> 1.4.6-py35_0  conda-forge      
    obvious-ci:   0.6.1-py35_0  conda-forge --> 0.6.1-py35_1  conda-forge      
    pyflakes:     1.2.3-py35_0  conda-forge --> 1.3.0-py35_0  defaults         
                                                                               
Proceed ([y]/n)?                                                               
```

**Comment by dopplershift** [comment] 2016-11-02 22:47
I think that's happening because you have flake8-3.0.4-py35_0, which I don't think had the pinning. On my macos system, I have flake8-3.0.4-py35_1. If I run `conda install pyflakes=1.3` I see:
```
Using Anaconda API: https://api.anaconda.org
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /Users/rmay/miniconda3/envs/py35:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pyflakes-1.3.0             |           py35_0          78 KB
    flake8-3.0.4               |           py35_0         258 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         336 KB

The following packages will be UPDATED:

    pyflakes: 1.2.3-py35_0 conda-forge --> 1.3.0-py35_0            

The following packages will be DOWNGRADED due to dependency conflicts:

    flake8:   3.0.4-py35_1 conda-forge --> 3.0.4-py35_0 conda-forge

Proceed ([y]/n)? 
```
So maybe if you just bump flake8, then `conda update --all` will have less ambiguity in the solution it can find?

**Comment by janschulz** [comment] 2016-11-02 23:13
Looks right:

```
λ conda install flake8
Fetching package metadata ...............
Solving package specifications: ..........

Package plan for installation in environment C:\portabel\miniconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    flake8-3.0.4               |           py35_1         120 KB  conda-forge
    conda-4.2.12               |           py35_0         446 KB  defaults
    ------------------------------------------------------------
                                           Total:         566 KB

The following packages will be UPDATED:

    conda:  4.2.11-py35_0 defaults    --> 4.2.12-py35_0 defaults
    flake8: 3.0.4-py35_0  conda-forge --> 3.0.4-py35_1  conda-forge

Proceed ([y]/n)? y
```

No idea why conda prefers the other way and not the "right" one... Seems that `flake8:   3.0.4-py35_0` should be removed?

**Comment by dopplershift** [comment] 2016-11-02 23:18
Not sure what the accepted method is, but it seems to come up a lot:

conda-forge/conda-forge.github.io#191
conda-forge/conda-forge.github.io#170
conda-forge/conda-forge.github.io#181
conda-forge/conda-forge.github.io#220
conda-forge/conda-forge.github.io#111

I'll see if any wisdom can be gained from the gitter channel.

**Comment by dopplershift** [comment] 2016-11-02 23:39
Closing since the issue is fixed. Whether to remove is TBD.

**Closed by dopplershift** 2016-11-02 23:39 UTC
